#!/usr/bin/env ruby

system("apm install sync-settings")
system("pyenv install 3.7.3")
system("pyenv global 3.7.3")
system("pip install psycopg2 stellar")
system("rbenv install 2.6.5")
system("rbenv global 2.6.5")
system("gem install bundler")

system("mkdir ~/src")
system("git clone git@github.com:delynn/zsh-files.git ~/src/")
