#!/usr/bin/env ruby

require 'irb/completion'
require 'irb/ext/save-history'

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT]  = true

begin
  require 'wirble'

  Wirble.init
  Wirble.colorize
rescue LoadError => error
  warn "Could not load the wirble gem."
end

begin
  require 'irbtools'
rescue LoadError => error
  warn "Could not load the irbtools gem."
end
