export HOMEBREW_BUNDLE_FILE="~/.Brewfile"
export DOCKER_HOST='tcp://docker.local:2375'
export DISABLE_SPRING=true
export EDITOR='atom'

# Ensure languages are set
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
