# Load Antigen
source /usr/local/share/antigen/antigen.zsh

# Anitgen in the oh-my-zsh's library.
antigen use oh-my-zsh

# Antigen Bundles from robbyrussell's oh-my-zsh
antigen bundle brew
antigen bundle bundler
antigen bundle pyenv
antigen bundle rbenv
antigen bundle ruby
antigen bundle rails
antigen bundle vscode

# Antigen Bundles
antigen bundle delynn/zsh-files
antigen bundle lukechilds/zsh-nvm
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# Antigen Theme
antigen theme delynn/zsh-files themes/delynn

antigen apply

heroku autocomplete:script zsh

# direnv
eval "$(direnv hook zsh)"

# Added by Krypton
export GPG_TTY=$(tty)
